import time
print("Let's Start to Hack tha Nasa")
time.sleep(3)
print(" ")
print(" ")
print("Please Wait till 100%... ")
print(" ")
print(" ")
time.sleep(3)
for i in range (100):
	print(i,"%")
	print("."*i)
	print(" ")
	print(" ")
	time.sleep(3)
print("Nasa is Successfully Hacked.. Please Wait..")
print(10)
print(" ")
print(" ")
print("404 Error")
time.sleep(3)
print(" ")
print(" ")
print("You can't Enter to NASA Server. Your Data Limit is 0 KB...")
time.sleep(2)
print(" ")
print(" ")
print(" ")
time.sleep(2)
print("Created by B2A6K D3V1L-MHK")
print(" ")
print(" ")
print("Sorry For Waste Your Time. ")
print("Use Your Time for usefull things.. ")
print("Good Bye.. ")
print("Happy Hacking...")
